name: Deploy Javadoc

on:
  push:
    branches:
      - dev
      - javadocs
  pull_request:
    types: [opened, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc
        uses: OneLemonyBoi/Javadoc-publisher.yml@0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 17
          target-folder: javadoc 
          project: gradle